In [1]:
import os
import pandas as pd
import numpy as np

In [11]:
df7 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\train\3.승인매출정보\201807_train_승인매출정보.parquet")
df8 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\train\3.승인매출정보\201808_train_승인매출정보.parquet")
df9 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\train\3.승인매출정보\201809_train_승인매출정보.parquet")
df10 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\train\3.승인매출정보\201810_train_승인매출정보.parquet")
df11 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\train\3.승인매출정보\201811_train_승인매출정보.parquet")
df12 = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\train\3.승인매출정보\201812_train_승인매출정보.parquet")

In [ ]:
dfs = [df7, df8, df9, df10, df11, df12]
merged_df = pd.concat(dfs, ignore_index=True)

In [15]:
for col, dtype in merged_df.dtypes.items():
    if dtype == 'float64':
        merged_df[col] = merged_df[col].astype('float32')
    elif dtype == 'int64':
        merged_df[col] = merged_df[col].astype('int32')

In [16]:
merged_df.to_parquet("3.승인정보_all_month.parquet")

In [17]:
df = pd.read_parquet(r"C:\Users\rtc32\OneDrive\바탕 화면\final_project\project\3.승인정보_all_month.parquet")

In [18]:
# 고유값이 1개인 컬럼 드랍
"""['이용건수_부분무이자_B0M', '이용금액_부분무이자_B0M', '여유_여행이용금액', '납부_렌탈료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액',
  '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', 'RP건수_유선방송_B0M', 'RP건수_건강_B0M', 
 'RP후경과월_유선방송', 'RP후경과월_건강', '증감_RP건수_유선방송_전월', '증감_RP건수_건강_전월', '이용개월수_당사페이_R6M', '이용금액_당사페이_R6M', 
'이용금액_당사기타_R6M', '이용건수_당사페이_R6M', '이용건수_당사기타_R6M', '이용금액_당사페이_R3M', '이용금액_당사기타_R3M', '이용건수_당사페이_R3M', 
'이용건수_당사기타_R3M', '이용금액_당사페이_B0M', '이용금액_당사기타_B0M', '이용건수_당사페이_B0M', '이용건수_당사기타_B0M', '승인거절건수_입력오류_B0M', '승인거절건수_기타_B0M']
"""
unique_cols = [col for col in df.columns if df[col].nunique() == 1]
df = df.drop(columns=unique_cols)
print(f"드랍된 컬럼: {unique_cols}")

드랍된 컬럼: ['이용건수_부분무이자_B0M', '이용금액_부분무이자_B0M', '여유_여행이용금액', '납부_렌탈료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', 'RP건수_유선방송_B0M', 'RP건수_건강_B0M', 'RP후경과월_유선방송', 'RP후경과월_건강', '증감_RP건수_유선방송_전월', '증감_RP건수_건강_전월', '이용개월수_당사페이_R6M', '이용금액_당사페이_R6M', '이용금액_당사기타_R6M', '이용건수_당사페이_R6M', '이용건수_당사기타_R6M', '이용금액_당사페이_R3M', '이용금액_당사기타_R3M', '이용건수_당사페이_R3M', '이용건수_당사기타_R3M', '이용금액_당사페이_B0M', '이용금액_당사기타_B0M', '이용건수_당사페이_B0M', '이용건수_당사기타_B0M', '승인거절건수_입력오류_B0M', '승인거절건수_기타_B0M']

In [19]:
print(f"컬럼 총 개수: {df.shape[1]}")

컬럼 총 개수: 375

In [20]:
print(f"드랍된 컬럼 개수: {len(unique_cols)}")

드랍된 컬럼 개수: 31

In [21]:
# 범주형 데이터 중 결측치가 있는 컬럼을 찾아 '기타'로 채우기
cat_cols = df.select_dtypes(include=['object', 'category']).columns
for col in cat_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna('기타')
        print(f"{col} 컬럼의 결측치를 '기타'로 채움")

_1순위업종 컬럼의 결측치를 '기타'로 채움
_2순위업종 컬럼의 결측치를 '기타'로 채움
_3순위업종 컬럼의 결측치를 '기타'로 채움
_1순위쇼핑업종 컬럼의 결측치를 '기타'로 채움
_2순위쇼핑업종 컬럼의 결측치를 '기타'로 채움
_3순위쇼핑업종 컬럼의 결측치를 '기타'로 채움
_1순위교통업종 컬럼의 결측치를 '기타'로 채움
_2순위교통업종 컬럼의 결측치를 '기타'로 채움
_3순위교통업종 컬럼의 결측치를 '기타'로 채움
_1순위여유업종 컬럼의 결측치를 '기타'로 채움
_2순위여유업종 컬럼의 결측치를 '기타'로 채움
_3순위여유업종 컬럼의 결측치를 '기타'로 채움
_1순위납부업종 컬럼의 결측치를 '기타'로 채움
_2순위납부업종 컬럼의 결측치를 '기타'로 채움
_3순위납부업종 컬럼의 결측치를 '기타'로 채움
최종카드론_신청경로코드 컬럼의 결측치를 '기타'로 채움

,기준년월,ID,최종이용일자_기본,최종이용일자_신판,최종이용일자_CA,최종이용일자_카드론,최종이용일자_체크,최종이용일자_일시불,최종이용일자_할부,이용건수_신용_B0M,...,신청건수_ATM_CL_R6M,승인거절건수_B0M,승인거절건수_한도초과_B0M,승인거절건수_BL_B0M,승인거절건수_R3M,승인거절건수_한도초과_R3M,승인거절건수_BL_R3M,승인거절건수_입력오류_R3M,승인거절건수_기타_R3M,이용금액대
0,0,0,20180719,20180713,20180719,10101,20180203,20180709,20180713,11,...,0,0,0,0,3,3,0,0,0,0
1,0,1,20180719,20180719,20170728,20170327,10101,20180719,20171231,13,...,0,0,0,0,3,3,0,0,0,2
2,0,2,20180706,20180706,20180706,20151119,20141230,20180706,20180627,12,...,0,0,0,0,0,0,0,0,0,0
3,0,3,20180721,20180715,20180721,10101,20141111,20180704,20180715,6,...,0,0,0,0,3,3,0,0,0,0
4,0,4,20180124,20180124,10101,10101,20180512,20180124,10101,-2,...,0,0,0,0,0,0,0,0,0,5

In [ ]:
# 날짜(YYYYMMDD) 또는 '사용하지 않음'(예: 10101) 패턴을 가진 int 컬럼 자동 탐지 및 전처리

def is_date_or_unused_col(series):
    # int 타입, 값이 100000 이하(사용안함) 또는 8자리(YYYYMMDD)인 값이 많으면 True
    if not np.issubdtype(series.dtype, np.integer):
        return False
    vals = series.dropna().unique()
    # 8자리(YYYYMMDD)와 100000 이하 값이 전체의 90% 이상이면 해당 패턴으로 간주
    date_like = sum((v > 10000000) & (v < 30000000) for v in vals)
    unused_like = sum(v == 10101 for v in vals)
    ratio = (date_like + unused_like) / len(vals) if len(vals) > 0 else 0
    return ratio > 0.9

for col in df.columns:
    if is_date_or_unused_col(df[col]):
        def parse_date_or_unused(x):
            if x == 10101:
                return np.nan
            try:
                return pd.to_datetime(str(int(x)), format='%Y%m%d')
            except:
                return np.nan
        df[col] = df[col].apply(parse_date_or_unused)
        print(f"{col} 컬럼을 날짜/10101(NaT) 패턴으로 자동 전처리")

최종이용일자_기본 컬럼을 날짜/10101(NaN) 패턴으로 자동 전처리
최종이용일자_신판 컬럼을 날짜/10101(NaN) 패턴으로 자동 전처리
최종이용일자_CA 컬럼을 날짜/10101(NaN) 패턴으로 자동 전처리
최종이용일자_카드론 컬럼을 날짜/10101(NaN) 패턴으로 자동 전처리
최종이용일자_체크 컬럼을 날짜/10101(NaN) 패턴으로 자동 전처리
최종이용일자_일시불 컬럼을 날짜/10101(NaN) 패턴으로 자동 전처리
최종이용일자_할부 컬럼을 날짜/10101(NaN) 패턴으로 자동 전처리

In [23]:
# '최종카드론_금융상환방식코드' 컬럼의 결측치를 최빈값으로 채우기
df['최종카드론_금융상환방식코드'] = df['최종카드론_금융상환방식코드'].fillna(df['최종카드론_금융상환방식코드'].mode()[0])

In [24]:
df['최종카드론_금융상환방식코드'] = df['최종카드론_금융상환방식코드'].astype('object')
print(df['최종카드론_금융상환방식코드'].dtype)

object

In [25]:
df['최종이용일자_기본'].head()

0   2018-07-19
1   2018-07-19
2   2018-07-06
3   2018-07-21
4   2018-01-24
Name: 최종이용일자_기본, dtype: datetime64[ns]

In [26]:
df['최종카드론_대출일자'] = pd.to_datetime(df['최종카드론_대출일자'], format='%Y%m%d', errors='coerce')

In [ ]:
#결측치 앞뒤날짜기준으로
df['최종카드론_대출일자'] = df['최종카드론_대출일자'].fillna(method='ffill').fillna(method='bfill')

C:\Users\rtc32\AppData\Local\Temp\ipykernel_17636\3955546613.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['최종카드론_대출일자'] = df['최종카드론_대출일자'].fillna(method='ffill').fillna(method='bfill')

In [29]:
#상관계수가 1인 컬럼제거 할부건수_부분_12MR12M <-> 이용건수부분무이자_R12M : 1.0

df = df.drop(columns=['이용건수_부분무이자_R12M'])

In [30]:
for col in df.columns:
    print(f"컬럼명: {col}")
    print(f" - 데이터 타입: {df[col].dtype}")
    print(f" - 고유값(최대 10개): {df[col].unique()[:10]}")
    print("-" * 40)

컬럼명: 기준년월
 - 데이터 타입: int32
 - 고유값(최대 10개): [201807 201808 201809 201810 201811 201812]
----------------------------------------
컬럼명: ID
 - 데이터 타입: object
 - 고유값(최대 10개): ['TRAIN_000000' 'TRAIN_000001' 'TRAIN_000002' 'TRAIN_000003'
 'TRAIN_000004' 'TRAIN_000005' 'TRAIN_000006' 'TRAIN_000007'
 'TRAIN_000008' 'TRAIN_000009']
----------------------------------------
컬럼명: 최종이용일자_기본
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-07-19 00:00:00', '2018-07-06 00:00:00', '2018-07-21 00:00:00',
 '2018-01-24 00:00:00', '2016-04-25 00:00:00', '2018-07-31 00:00:00',
 '2018-07-26 00:00:00', '2018-07-10 00:00:00',                 'NaT',
 '2018-06-05 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_신판
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-07-13 00:00:00', '2018-07-19 00:00:00', '2018-07-06 00:00:00',
 '2018-07-15 00:00:00', '2018-01-24 00:00:00', '2016-04-25 00:00:00',
 '2018-07-31 00:00:00', '2018-07-26 00:00:00', '2018-07-10 00:00:00',
                 'NaT']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_CA
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-07-19 00:00:00', '2017-07-28 00:00:00', '2018-07-06 00:00:00',
 '2018-07-21 00:00:00',                 'NaT', '2013-08-26 00:00:00',
 '2015-07-08 00:00:00', '2014-04-29 00:00:00', '2015-11-07 00:00:00',
 '2018-06-16 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_카드론
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
[                'NaT', '2017-03-27 00:00:00', '2015-11-19 00:00:00',
 '2018-06-05 00:00:00', '2018-02-06 00:00:00', '2016-06-30 00:00:00',
 '2015-01-14 00:00:00', '2015-05-14 00:00:00', '2014-10-18 00:00:00',
 '2015-07-02 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_체크
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-02-03 00:00:00',                 'NaT', '2014-12-30 00:00:00',
 '2014-11-11 00:00:00', '2018-05-12 00:00:00', '2018-07-31 00:00:00',
 '2015-01-20 00:00:00', '2018-07-21 00:00:00', '2018-07-07 00:00:00',
 '2014-03-01 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_일시불
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-07-09 00:00:00', '2018-07-19 00:00:00', '2018-07-06 00:00:00',
 '2018-07-04 00:00:00', '2018-01-24 00:00:00', '2016-04-25 00:00:00',
 '2018-07-31 00:00:00', '2018-07-26 00:00:00', '2018-07-10 00:00:00',
                 'NaT']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 최종이용일자_할부
 - 데이터 타입: datetime64[ns]
 - 고유값(최대 10개): <DatetimeArray>
['2018-07-13 00:00:00', '2017-12-31 00:00:00', '2018-06-27 00:00:00',
 '2018-07-15 00:00:00',                 'NaT', '2017-05-28 00:00:00',
 '2018-03-20 00:00:00', '2018-04-11 00:00:00', '2015-07-01 00:00:00',
 '2018-03-29 00:00:00']
Length: 10, dtype: datetime64[ns]
----------------------------------------
컬럼명: 이용건수_신용_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [11 13 12  6 -2  0  9 27 77  1]
----------------------------------------
컬럼명: 이용건수_신판_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 9 13 10  4 -2  0 27 77  1 -3]
----------------------------------------
컬럼명: 이용건수_일시불_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 8 13 10  3 -2  0  9 27 77  1]
----------------------------------------
컬럼명: 이용건수_할부_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [1 0 2 3]
----------------------------------------
컬럼명: 이용건수_할부_유이자_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용건수_할부_무이자_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [1 0 2]
----------------------------------------
컬럼명: 이용건수_CA_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [2 0 1 3]
----------------------------------------
컬럼명: 이용건수_체크_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  8 12 41 23 10 19 32 31 18]
----------------------------------------
컬럼명: 이용건수_카드론_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용금액_일시불_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 1995  2862  5854   387     0  3334  2728 24242  2965  3410]
----------------------------------------
컬럼명: 이용금액_할부_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  4961  8490 10596  3495  3946  3700  8997  3640  4410]
----------------------------------------
컬럼명: 이용금액_할부_유이자_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 4457 5432 4359 4397 3771 3927 4483 4595 5218]
----------------------------------------
컬럼명: 이용금액_할부_무이자_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 4961 4032 5163 3495 3946 3700 4637 3640 4410]
----------------------------------------
컬럼명: 이용금액_CA_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [12209     0 14306 13789  9510 10914 18817  5883 12820 10395]
----------------------------------------
컬럼명: 이용금액_체크_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 1525 2544 8877 4488 1721 4718 7004 5493 3092]
----------------------------------------
컬럼명: 이용금액_카드론_B0M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 68522 70061 69768 69695 69010 70558 70824 69610 69788]
----------------------------------------
컬럼명: 이용후경과월_신용
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  6 12  1  8  9  4 10 11  2]
----------------------------------------
컬럼명: 이용후경과월_신판
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  6 12  1  8  9  4  2 10 11]
----------------------------------------
컬럼명: 이용후경과월_일시불
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  6 12  2  9 11  1  8 10  3]
----------------------------------------
컬럼명: 이용후경과월_할부
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 2  9  0  1 12  4  5  7  3  8]
----------------------------------------
컬럼명: 이용후경과월_할부_유이자
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 7  9 12  1  8  4  3  0  5  2]
----------------------------------------
컬럼명: 이용후경과월_할부_무이자
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 2  9  0  1 12  4  5  7  3  8]
----------------------------------------
컬럼명: 이용후경과월_부분무이자
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  2  7  5  1  8  6  4  9 10]
----------------------------------------
컬럼명: 이용후경과월_CA
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0 12  1  6  2  7 11  9  4  5]
----------------------------------------
컬럼명: 이용후경과월_체크
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 5 12  2  0  6  1  9 11  4  8]
----------------------------------------
컬럼명: 이용후경과월_카드론
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  1  5  2  8  4  3  7  6  9]
----------------------------------------
컬럼명: 이용건수_신용_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [165 204 148 105  -1   0 369 863  34 129]
----------------------------------------
컬럼명: 이용건수_신판_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [146 202 134  85  -1   0 148 369 863  34]
----------------------------------------
컬럼명: 이용건수_일시불_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [143 202 131  74  -1   0 148 366 863  27]
----------------------------------------
컬럼명: 이용건수_할부_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 3  0 11  7  9  4 24 36 12  8]
----------------------------------------
컬럼명: 이용건수_할부_유이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  5  4 12  8 13  7  6  3 10]
----------------------------------------
컬럼명: 이용건수_할부_무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 3  0  6  7  5  4 12 28  8 15]
----------------------------------------
컬럼명: 이용건수_CA_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [19  2 14 20  0  4  6  1 12  3]
----------------------------------------
컬럼명: 이용건수_체크_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 30   0  24  85 123 472 281 141 135 381]
----------------------------------------
컬럼명: 이용건수_카드론_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2 3]
----------------------------------------
컬럼명: 이용금액_일시불_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 20667  54341  55656  10753  -2129      0  51382  25691 360859  34884]
----------------------------------------
컬럼명: 이용금액_할부_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 9431  6134 10561 22129     0  3939  4014  2204 34252  6374]
----------------------------------------
컬럼명: 이용금액_할부_유이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 3602  4058     0 10031  3939  6397 22210  4067 22016  4801]
----------------------------------------
컬럼명: 이용금액_할부_무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 5828  2076 10561 12098     0  4014  2204 25891  6374 12642]
----------------------------------------
컬럼명: 이용금액_부분무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 8361 7983 8163 7682 7754 7922 8158 8001 8045]
----------------------------------------
컬럼명: 이용금액_CA_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [103812   4297 374552 207745      0   9797  18355  11167  72974   3902]
----------------------------------------
컬럼명: 이용금액_체크_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 6474  -414   871 10754   558   144 13933  5588  -332  1351]
----------------------------------------
컬럼명: 이용금액_카드론_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [     0  46585  46741 134652  46762 140841  46578  47052  46657  47222]
----------------------------------------
컬럼명: 최대이용금액_일시불_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 4906 10407 10112  3075    62     0  7318  3581 47166  6681]
----------------------------------------
컬럼명: 최대이용금액_할부_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  4607 15453  8874  3646  3105  5979 25808 10391  8227]
----------------------------------------
컬럼명: 최대이용금액_할부_유이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  4607  3475  3646  2494 11037  4966 17410  3096  9121]
----------------------------------------
컬럼명: 최대이용금액_할부_무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  2321 15453  8874  3105  5979 25808 10391  8227  7351]
----------------------------------------
컬럼명: 최대이용금액_부분무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 7839 7237 7219 7354 7410 7343 7508 7472 7240]
----------------------------------------
컬럼명: 최대이용금액_CA_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [11710  3377 65977 19698     0  5127  6735  6150 12852  3381]
----------------------------------------
컬럼명: 최대이용금액_체크_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 1020     0  3324  3372  5158 24605  7714  3900  7980 14033]
----------------------------------------
컬럼명: 최대이용금액_카드론_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [     0  41320  41305  76400 141210  20752  74408  20944  74166  20575]
----------------------------------------
컬럼명: 이용개월수_신용_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  9  1  0  7  2 11 10  3  6]
----------------------------------------
컬럼명: 이용개월수_신판_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  9  1  0  7  2 11 10  3  6]
----------------------------------------
컬럼명: 이용개월수_일시불_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  9  7  1  0  6  2 11 10  8]
----------------------------------------
컬럼명: 이용개월수_할부_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 5  2  8  0  1  4 10 11  7  3]
----------------------------------------
컬럼명: 이용개월수_할부_유이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [1 0 4 3 2 5]
----------------------------------------
컬럼명: 이용개월수_할부_무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [4 1 2 5 0 3 7 9 8 6]
----------------------------------------
컬럼명: 이용개월수_부분무이자_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용개월수_CA_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [12  2  8  0  3  5  7  1 10  6]
----------------------------------------
컬럼명: 이용개월수_체크_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 3  0  8 12  7  9  6  5  4  2]
----------------------------------------
컬럼명: 이용개월수_카드론_R12M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2]
----------------------------------------
컬럼명: 이용건수_신용_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 77  81  62  42  -2   8  55 177 455   1]
----------------------------------------
컬럼명: 이용건수_신판_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 67  81  56  32  -2   8  55 177 455   1]
----------------------------------------
컬럼명: 이용건수_일시불_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 64  81  54  26  -2   8  55 176 454  16]
----------------------------------------
컬럼명: 이용건수_할부_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 3  0  2  6  1  4 11 19  8  7]
----------------------------------------
컬럼명: 이용건수_할부_유이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  4  1 -1  2  3  5  6]
----------------------------------------
컬럼명: 이용건수_할부_무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 3  0  2  1  4  7 15  8  9 11]
----------------------------------------
컬럼명: 이용건수_부분무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용건수_CA_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [10  0  6  2  3  1  9 12  7  4]
----------------------------------------
컬럼명: 이용건수_체크_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 22   0   8  40  52 258 139  59  69 200]
----------------------------------------
컬럼명: 이용건수_카드론_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2]
----------------------------------------
컬럼명: 이용금액_일시불_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [  8380  19426  35136  -7031    957      0  22495  19968 131028  19802]
----------------------------------------
컬럼명: 이용금액_할부_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [-1654     0 14871 16531 -1614 25136  6030  8480  5119  6915]
----------------------------------------
컬럼명: 이용금액_할부_유이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  7992  4799 13658 24347  2606  8646  8534  6680  2387]
----------------------------------------
컬럼명: 이용금액_할부_무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [-1654     0 14871  8538 -1614 25136  6030  8480  5119  2116]
----------------------------------------
컬럼명: 이용금액_부분무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 10214 10532 10509 10418 10383 10710 10591 10271 10027]
----------------------------------------
컬럼명: 이용금액_CA_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 59452      0 134858  95337   6081   8023   7934  41584  16512   4237]
----------------------------------------
컬럼명: 이용금액_체크_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 4090     0  3610  5993 10281 58336 27145  8593 18542 43453]
----------------------------------------
컬럼명: 이용금액_카드론_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [     0  56122 102000  48771  58179  40215  44239  68206  85039  62456]
----------------------------------------
컬럼명: 이용개월수_신용_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [6 1 0 3 5 4 2]
----------------------------------------
컬럼명: 이용개월수_신판_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [6 1 0 3 5 4 2]
----------------------------------------
컬럼명: 이용개월수_일시불_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [6 1 0 3 5 4 2]
----------------------------------------
컬럼명: 이용개월수_할부_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [2 0 4 1 6 5 3]
----------------------------------------
컬럼명: 이용개월수_할부_유이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 2 3 1 4 5 6]
----------------------------------------
컬럼명: 이용개월수_할부_무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [2 0 3 1 6 4 5]
----------------------------------------
컬럼명: 이용개월수_부분무이자_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용개월수_CA_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [6 0 5 1 3 4 2]
----------------------------------------
컬럼명: 이용개월수_체크_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [1 0 4 6 5 2 3]
----------------------------------------
컬럼명: 이용개월수_카드론_R6M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2]
----------------------------------------
컬럼명: 이용건수_신용_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 27  43  36  21   0  79 246   8 193 100]
----------------------------------------
컬럼명: 이용건수_신판_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 22  43  33  16   0  21  79 246   8 193]
----------------------------------------
컬럼명: 이용건수_일시불_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 21  43  31  13   0  79 245  -2   8 193]
----------------------------------------
컬럼명: 이용건수_할부_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [1 0 2 3 5 7 4 6 8 9]
----------------------------------------
컬럼명: 이용건수_할부_유이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 0  2  1  3 -1]
----------------------------------------
컬럼명: 이용건수_할부_무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 1  0  2  3  5  4  6 -1]
----------------------------------------
컬럼명: 이용건수_부분무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용건수_CA_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [5 0 3 2 1 4 7 6 8 9]
----------------------------------------
컬럼명: 이용건수_체크_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [  0  20  26 133  75  30  35  99  95  47]
----------------------------------------
컬럼명: 이용건수_카드론_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용금액_일시불_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 2877 14316 15694 -2710 -3383  -210 11254  9105 63825   331]
----------------------------------------
컬럼명: 이용금액_할부_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 1949   -25 11458 11662    -1   -23    -4    19    18    24]
----------------------------------------
컬럼명: 이용금액_할부_유이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  5989  3801  8504 13824  5418  4470  3045  7489  4328]
----------------------------------------
컬럼명: 이용금액_할부_무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 1984     0 11308  5643 11608  7260  5143  5944 13831  4794]
----------------------------------------
컬럼명: 이용금액_부분무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [-34 -25 150  29  -1 -23  -4  19  18  24]
----------------------------------------
컬럼명: 이용금액_CA_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [37417     0 43002 47830  5424  4076  7103 20641 11271 30468]
----------------------------------------
컬럼명: 이용금액_체크_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0  1087  3131  5241 29197 14570  4733  9578 21735 17633]
----------------------------------------
컬럼명: 이용금액_카드론_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0 76408 89956 74771 66830 78661 71474 71044 84570 74828]
----------------------------------------
컬럼명: 이용개월수_신용_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [3 0 1 2]
----------------------------------------
컬럼명: 이용개월수_신판_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [3 0 1 2]
----------------------------------------
컬럼명: 이용개월수_일시불_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [3 0 1 2]
----------------------------------------
컬럼명: 이용개월수_할부_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [1 0 2 3]
----------------------------------------
컬럼명: 이용개월수_할부_유이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 2 3]
----------------------------------------
컬럼명: 이용개월수_할부_무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [1 0 3 2]
----------------------------------------
컬럼명: 이용개월수_부분무이자_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용개월수_CA_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [3 0 2 1]
----------------------------------------
컬럼명: 이용개월수_체크_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1 3 2]
----------------------------------------
컬럼명: 이용개월수_카드론_R3M
 - 데이터 타입: int32
 - 고유값(최대 10개): [0 1]
----------------------------------------
컬럼명: 이용가맹점수
 - 데이터 타입: int32
 - 고유값(최대 10개): [ 6 32 27 10  0  1 24 97 83 48]
----------------------------------------
컬럼명: 이용금액_해외
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 1885 1648 1331 2077 1342 1300 1561 1460 2562]
----------------------------------------
컬럼명: 쇼핑_도소매_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0  645 1038 2162 1567 1434  638 2767  468 2385]
----------------------------------------
컬럼명: 쇼핑_백화점_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0  751  819  679  879 1274  873  814  856  742]
----------------------------------------
컬럼명: 쇼핑_마트_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0  924  801  913 2590 1598 1332  773 1041 1278]
----------------------------------------
컬럼명: 쇼핑_슈퍼마켓_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0  435  504  487  225  506 1786 1929 1045  399]
----------------------------------------
컬럼명: 쇼핑_편의점_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0  315  239  267 1652  705  377  234  181  196]
----------------------------------------
컬럼명: 쇼핑_아울렛_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [  0 642 487 559 599 607 652 613 666 574]
----------------------------------------
컬럼명: 쇼핑_온라인_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [    0   272  6094   875   984 47249  7643  2230 12350   998]
----------------------------------------
컬럼명: 쇼핑_기타_이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [242 289   0 398 384 355 258 252 254 283]
----------------------------------------
컬럼명: 교통_주유이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [   0 1215 1362 1361 4347 2958 2163 1356 1273 1863]
----------------------------------------
컬럼명: 교통_정비이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [  0 277 842 483 427 312 273 701 456 621]
----------------------------------------
컬럼명: 교통_통행료이용금액
 - 데이터 타입: int32
 - 고유값(최대 10개): [  0 284 294 286 280 296 289 283 316 304]
----------------------------------------
컬럼명: 교통_버스지하철이용금액
 - 데이터 타입: int32

In [31]:
df.to_parquet("3.승인매출정보_전처리완.parquet")