In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 차원 축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 군집
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift
from sklearn.cluster import estimate_bandwidth


# 학습 모델 저장을 위한 라이브러리
import pickle

In [2]:
# parquet 파일 데이터를 읽어온다.
df1 = pd.read_parquet('open/train/6.채널정보/201807_train_채널정보.parquet')
df2 = pd.read_parquet('open/train/6.채널정보/201808_train_채널정보.parquet')
df3 = pd.read_parquet('open/train/6.채널정보/201809_train_채널정보.parquet')
df4 = pd.read_parquet('open/train/6.채널정보/201810_train_채널정보.parquet')
df5 = pd.read_parquet('open/train/6.채널정보/201811_train_채널정보.parquet')
df6 = pd.read_parquet('open/train/6.채널정보/201812_train_채널정보.parquet')

In [3]:
# 월별 데이터 프레임을 합친다.
all_df = pd.concat([df1, df2, df3, df4, df5, df6])
all_df.reset_index(inplace=True, drop=True)
all_df

,기준년월,ID,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,인입일수_ARS_R6M,인입월수_ARS_R6M,인입후경과월_ARS,인입횟수_ARS_B0M,이용메뉴건수_ARS_B0M,인입일수_ARS_B0M,...,당사PAY_방문횟수_R6M,당사PAY_방문월수_R6M,당사멤버쉽_방문횟수_B0M,당사멤버쉽_방문횟수_R6M,당사멤버쉽_방문월수_R6M,OS구분코드,홈페이지_금융건수_R6M,홈페이지_선결제건수_R6M,홈페이지_금융건수_R3M,홈페이지_선결제건수_R3M
0,201807,TRAIN_000000,10회 이상,10회 이상,8,6,0,2,6,2,...,0,0,22,221,6,Android,0,0,0,0
1,201807,TRAIN_000001,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
2,201807,TRAIN_000002,1회 이상,1회 이상,1,1,0,2,5,1,...,0,0,0,0,0,Android,11,6,5,5
3,201807,TRAIN_000003,10회 이상,10회 이상,10,6,0,2,6,2,...,0,0,23,219,6,Android,0,0,0,0
4,201807,TRAIN_000004,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,Android,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
2399996,201812,TRAIN_399996,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,1,None,0,0,0,0
2399997,201812,TRAIN_399997,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
2399998,201812,TRAIN_399998,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
2399999,201812,TRAIN_399999,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0

In [6]:
# info 출력 시 컬럼 생략하지 않도록 설정
pd.set_option('display.max_info_columns', 200)  # 200개 이상 컬럼이 있어도 다 보여줘
pd.set_option('display.max_columns', None)      # 모든 컬럼 표시 (보조 설정)
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400000 entries, 0 to 2399999
Data columns (total 105 columns):
 #    Column             Dtype
---   ------             -----
 0    기준년월               int64
 1    ID                 object
 2    인입횟수_ARS_R6M       object
 3    이용메뉴건수_ARS_R6M     object
 4    인입일수_ARS_R6M       int64
 5    인입월수_ARS_R6M       int64
 6    인입후경과월_ARS         int64
 7    인입횟수_ARS_B0M       int64
 8    이용메뉴건수_ARS_B0M     int64
 9    인입일수_ARS_B0M       int64
 10   방문횟수_PC_R6M        object
 11   방문일수_PC_R6M        object
 12   방문월수_PC_R6M        int64
 13   방문후경과월_PC_R6M      int64
 14   방문횟수_앱_R6M         object
 15   방문일수_앱_R6M         int64
 16   방문월수_앱_R6M         int64
 17   방문후경과월_앱_R6M       int64
 18   방문횟수_모바일웹_R6M      int64
 19   방문일수_모바일웹_R6M      int64
 20   방문월수_모바일웹_R6M      int64
 21   방문후경과월_모바일웹_R6M    int64
 22   방문횟수_PC_B0M        int64
 23   방문일수_PC_B0M        int64
 24   방문횟수_앱_B0M         int64
 25   방문일수_앱_B0M         int64
 26   방문횟수_모바일웹_B0M      int64
 27   방문일수_모바일웹_B0M      int64
 28   인입횟수_IB_R6M        int64
 29   인입횟수_금융_IB_R6M     int64
 30   인입일수_IB_R6M        int64
 31   인입월수_IB_R6M        int64
 32   이용메뉴건수_IB_R6M      int64
 33   인입후경과월_IB_R6M      int64
 34   인입횟수_IB_B0M        int64
 35   인입일수_IB_B0M        int64
 36   이용메뉴건수_IB_B0M      int64
 37   인입불만횟수_IB_R6M      int64
 38   인입불만일수_IB_R6M      int64
 39   인입불만월수_IB_R6M      int64
 40   인입불만후경과월_IB_R6M    int64
 41   인입불만횟수_IB_B0M      int64
 42   인입불만일수_IB_B0M      int64
 43   상담건수_B0M           int64
 44   IB문의건수_사용승인내역_B0M  int64
 45   IB문의건수_한도_B0M      int64
 46   IB문의건수_선결제_B0M     int64
 47   IB문의건수_결제_B0M      int64
 48   IB문의건수_할부_B0M      int64
 49   IB문의건수_정보변경_B0M    int64
 50   IB문의건수_결제일변경_B0M   int64
 51   IB문의건수_명세서_B0M     int64
 52   IB문의건수_비밀번호_B0M    int64
 53   IB문의건수_SMS_B0M     int64
 54   IB문의건수_APP_B0M     int64
 55   IB문의건수_부대서비스_B0M   int64
 56   IB문의건수_포인트_B0M     int64
 57   IB문의건수_카드발급_B0M    int64
 58   IB문의건수_BL_B0M      int64
 59   IB문의건수_분실도난_B0M    int64
 60   IB문의건수_CA_B0M      int64
 61   IB문의건수_CL_RV_B0M   int64
 62   IB문의건수_CS_B0M      int64
 63   IB상담건수_VOC_B0M     int64
 64   IB상담건수_VOC민원_B0M   int64
 65   IB상담건수_VOC불만_B0M   int64
 66   IB상담건수_금감원_B0M     int64
 67   상담건수_R6M           int64
 68   IB문의건수_사용승인내역_R6M  int64
 69   IB문의건수_한도_R6M      int64
 70   IB문의건수_선결제_R6M     int64
 71   IB문의건수_결제_R6M      int64
 72   IB문의건수_할부_R6M      int64
 73   IB문의건수_정보변경_R6M    int64
 74   IB문의건수_결제일변경_R6M   int64
 75   IB문의건수_명세서_R6M     int64
 76   IB문의건수_비밀번호_R6M    int64
 77   IB문의건수_SMS_R6M     int64
 78   IB문의건수_APP_R6M     int64
 79   IB문의건수_부대서비스_R6M   int64
 80   IB문의건수_포인트_R6M     int64
 81   IB문의건수_카드발급_R6M    int64
 82   IB문의건수_BL_R6M      int64
 83   IB문의건수_분실도난_R6M    int64
 84   IB문의건수_CA_R6M      int64
 85   IB문의건수_CL_RV_R6M   int64
 86   IB문의건수_CS_R6M      int64
 87   IB상담건수_VOC_R6M     int64
 88   IB상담건수_VOC민원_R6M   int64
 89   IB상담건수_VOC불만_R6M   int64
 90   IB상담건수_금감원_R6M     int64
 91   불만제기건수_B0M         int64
 92   불만제기건수_R12M        int64
 93   불만제기후경과월_R12M      int64
 94   당사PAY_방문횟수_B0M     int64
 95   당사PAY_방문횟수_R6M     int64
 96   당사PAY_방문월수_R6M     int64
 97   당사멤버쉽_방문횟수_B0M     int64
 98   당사멤버쉽_방문횟수_R6M     int64
 99   당사멤버쉽_방문월수_R6M     int64
 100  OS구분코드             object
 101  홈페이지_금융건수_R6M      int64
 102  홈페이지_선결제건수_R6M     int64
 103  홈페이지_금융건수_R3M      int64
 104  홈페이지_선결제건수_R3M     int64
dtypes: int64(98), object(7)
memory usage: 1.9+ GB

In [25]:
missing_summary = all_df.isnull().sum()
missing_summary = missing_summary[missing_summary > 0]  # 결측치가 있는 컬럼만 필터링
print(missing_summary)

OS구분코드    1633566
dtype: int64

In [7]:
# 소수점 6자리까지 출력하고 지수 표기 비활성화
pd.set_option('display.float_format', '{:.0f}'.format)

In [8]:
for i in range(1, 104) :
    a1= all_df.iloc[:,i].describe()
    print(a1)
    print('-'*30)

count          2400000
unique          400000
top       TRAIN_000000
freq                 6
Name: ID, dtype: object
------------------------------
count     2400000
unique          2
top         1회 이상
freq      2328933
Name: 인입횟수_ARS_R6M, dtype: object
------------------------------
count     2400000
unique          4
top         1회 이상
freq      2313787
Name: 이용메뉴건수_ARS_R6M, dtype: object
------------------------------
count   2400000
mean          1
std           2
min           0
25%           0
50%           0
75%           1
max          12
Name: 인입일수_ARS_R6M, dtype: float64
------------------------------
count   2400000
mean          1
std           1
min           0
25%           0
50%           0
75%           1
max           6
Name: 인입월수_ARS_R6M, dtype: float64
------------------------------
count   2400000
mean          1
std           1
min           0
25%           0
50%           0
75%           0
max           5
Name: 인입후경과월_ARS, dtype: float64
------------------------------
count   2400000
mean          0
std           1
min           0
25%           0
50%           0
75%           0
max           3
Name: 인입횟수_ARS_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           1
min           0
25%           0
50%           0
75%           0
max           7
Name: 이용메뉴건수_ARS_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           2
Name: 인입일수_ARS_B0M, dtype: float64
------------------------------
count     2400000
unique          5
top         1회 이상
freq      2221841
Name: 방문횟수_PC_R6M, dtype: object
------------------------------
count     2400000
unique          4
top         1회 이상
freq      2236992
Name: 방문일수_PC_R6M, dtype: object
------------------------------
count   2400000
mean          0
std           2
min           0
25%           0
50%           0
75%           0
max           6
Name: 방문월수_PC_R6M, dtype: float64
------------------------------
count   2400000
mean          5
std           2
min           0
25%           6
50%           6
75%           6
max           6
Name: 방문후경과월_PC_R6M, dtype: float64
------------------------------
count     2400000
unique          9
top         1회 이상
freq      2082674
Name: 방문횟수_앱_R6M, dtype: object
------------------------------
count   2400000
mean          4
std          10
min           0
25%           0
50%           0
75%           0
max          64
Name: 방문일수_앱_R6M, dtype: float64
------------------------------
count   2400000
mean          1
std           2
min           0
25%           0
50%           0
75%           0
max           6
Name: 방문월수_앱_R6M, dtype: float64
------------------------------
count   2400000
mean          5
std           2
min           0
25%           6
50%           6
75%           6
max           6
Name: 방문후경과월_앱_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           1
min           0
25%           0
50%           0
75%           0
max          13
Name: 방문횟수_모바일웹_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           1
min           0
25%           0
50%           0
75%           0
max          12
Name: 방문일수_모바일웹_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           1
Name: 방문월수_모바일웹_R6M, dtype: float64
------------------------------
count   2400000
mean          6
std           0
min           0
25%           6
50%           6
75%           6
max           6
Name: 방문후경과월_모바일웹_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           1
min           0
25%           0
50%           0
75%           0
max           9
Name: 방문횟수_PC_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           1
min           0
25%           0
50%           0
75%           0
max           6
Name: 방문일수_PC_B0M, dtype: float64
------------------------------
count   2400000
mean          1
std           2
min           0
25%           0
50%           0
75%           0
max          16
Name: 방문횟수_앱_B0M, dtype: float64
------------------------------
count   2400000
mean          1
std           2
min           0
25%           0
50%           0
75%           0
max          11
Name: 방문일수_앱_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           5
Name: 방문횟수_모바일웹_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           4
Name: 방문일수_모바일웹_B0M, dtype: float64
------------------------------
count   2400000
mean          1
std           2
min           0
25%           0
50%           0
75%           1
max          15
Name: 인입횟수_IB_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: 인입횟수_금융_IB_R6M, dtype: float64
------------------------------
count   2400000
mean          1
std           1
min           0
25%           0
50%           0
75%           1
max           8
Name: 인입일수_IB_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           1
min           0
25%           0
50%           0
75%           1
max           6
Name: 인입월수_IB_R6M, dtype: float64
------------------------------
count   2400000
mean          1
std           1
min           0
25%           0
50%           0
75%           1
max           6
Name: 이용메뉴건수_IB_R6M, dtype: float64
------------------------------
count   2400000
mean          5
std           2
min           0
25%           5
50%           6
75%           6
max           6
Name: 인입후경과월_IB_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           3
Name: 인입횟수_IB_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           2
Name: 인입일수_IB_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           1
Name: 이용메뉴건수_IB_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: 인입불만횟수_IB_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: 인입불만일수_IB_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: 인입불만월수_IB_R6M, dtype: float64
------------------------------
count   2400000
mean          6
std           0
min           6
25%           6
50%           6
75%           6
max           6
Name: 인입불만후경과월_IB_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: 인입불만횟수_IB_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: 인입불만일수_IB_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           3
Name: 상담건수_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           1
Name: IB문의건수_사용승인내역_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_한도_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           1
Name: IB문의건수_선결제_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_결제_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_할부_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_정보변경_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_결제일변경_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_명세서_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_비밀번호_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_SMS_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_APP_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_부대서비스_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_포인트_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           1
Name: IB문의건수_카드발급_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_BL_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_분실도난_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_CA_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           1
Name: IB문의건수_CL_RV_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           4
Name: IB문의건수_CS_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB상담건수_VOC_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB상담건수_VOC민원_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB상담건수_VOC불만_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB상담건수_금감원_B0M, dtype: float64
------------------------------
count   2400000
mean          1
std           2
min           0
25%           0
50%           0
75%           2
max          13
Name: 상담건수_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           2
Name: IB문의건수_사용승인내역_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           2
Name: IB문의건수_한도_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           1
min           0
25%           0
50%           0
75%           0
max           6
Name: IB문의건수_선결제_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           2
Name: IB문의건수_결제_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           1
Name: IB문의건수_할부_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           1
Name: IB문의건수_정보변경_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           5
Name: IB문의건수_결제일변경_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_명세서_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           1
Name: IB문의건수_비밀번호_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           1
Name: IB문의건수_SMS_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB문의건수_APP_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           1
Name: IB문의건수_부대서비스_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           4
Name: IB문의건수_포인트_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           1
Name: IB문의건수_카드발급_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           1
Name: IB문의건수_BL_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           1
Name: IB문의건수_분실도난_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           8
Name: IB문의건수_CA_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           3
Name: IB문의건수_CL_RV_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           6
Name: IB문의건수_CS_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB상담건수_VOC_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB상담건수_VOC민원_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB상담건수_VOC불만_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: IB상담건수_금감원_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: 불만제기건수_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: 불만제기건수_R12M, dtype: float64
------------------------------
count   2400000
mean          7
std           6
min           0
25%           0
50%          12
75%          12
max          12
Name: 불만제기후경과월_R12M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: 당사PAY_방문횟수_B0M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: 당사PAY_방문횟수_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           0
min           0
25%           0
50%           0
75%           0
max           0
Name: 당사PAY_방문월수_R6M, dtype: float64
------------------------------
count   2400000
mean          1
std           7
min           0
25%           0
50%           0
75%           0
max          63
Name: 당사멤버쉽_방문횟수_B0M, dtype: float64
------------------------------
count   2400000
mean         11
std          46
min           0
25%           0
50%           0
75%           0
max         259
Name: 당사멤버쉽_방문횟수_R6M, dtype: float64
------------------------------
count   2400000
mean          1
std           2
min           0
25%           0
50%           0
75%           0
max           6
Name: 당사멤버쉽_방문월수_R6M, dtype: float64
------------------------------
count      766434
unique          2
top       Android
freq       594348
Name: OS구분코드, dtype: object
------------------------------
count   2400000
mean          1
std           2
min           0
25%           0
50%           0
75%           0
max          15
Name: 홈페이지_금융건수_R6M, dtype: float64
------------------------------
count   2400000
mean          1
std           3
min           0
25%           0
50%           0
75%           0
max          30
Name: 홈페이지_선결제건수_R6M, dtype: float64
------------------------------
count   2400000
mean          0
std           1
min           0
25%           0
50%           0
75%           0
max           8
Name: 홈페이지_금융건수_R3M, dtype: float64
------------------------------

In [12]:
all_df['방문월수_PC_R6M'].value_counts()

방문월수_PC_R6M
0    2064931
1     173058
6     161856
2        151
3          3
5          1
Name: count, dtype: int64

In [19]:
for i in range(1, 104) :
    a1= all_df.iloc[:,i].value_counts()
    print(a1)
    print('-'*30)

ID
TRAIN_000000    6
TRAIN_266650    6
TRAIN_266672    6
TRAIN_266671    6
TRAIN_266670    6
               ..
TRAIN_133331    6
TRAIN_133330    6
TRAIN_133329    6
TRAIN_133328    6
TRAIN_399999    6
Name: count, Length: 400000, dtype: int64
------------------------------
인입횟수_ARS_R6M
1회 이상     2328933
10회 이상      71067
Name: count, dtype: int64
------------------------------
이용메뉴건수_ARS_R6M
1회 이상     2313787
10회 이상      70027
30회 이상      10172
20회 이상       6014
Name: count, dtype: int64
------------------------------
인입일수_ARS_R6M
0     1683964
1      266478
2      200257
3       74634
4       39222
5       26364
6       21823
8       20994
9       19334
7       19244
10      15987
12       9904
11       1795
Name: count, dtype: int64
------------------------------
인입월수_ARS_R6M
0    1696515
1     410652
2     208764
6      78256
3       4967
4        667
5        179
Name: count, dtype: int64
------------------------------
인입후경과월_ARS
0    1880190
5     128172
4     117176
3     104298
2      91727
1      78437
Name: count, dtype: int64
------------------------------
인입횟수_ARS_B0M
0    2251753
2     138258
3       9987
1          2
Name: count, dtype: int64
------------------------------
이용메뉴건수_ARS_B0M
0    2250867
5     120284
6      25115
4       3733
7          1
Name: count, dtype: int64
------------------------------
인입일수_ARS_B0M
0    2251797
2     102430
1      45773
Name: count, dtype: int64
------------------------------
방문횟수_PC_R6M
1회 이상     2221841
20회 이상      77377
10회 이상      67199
30회 이상      32730
40회 이상        853
Name: count, dtype: int64
------------------------------
방문일수_PC_R6M
1회 이상     2236992
10회 이상     102991
20회 이상      57986
30회 이상       2031
Name: count, dtype: int64
------------------------------
방문월수_PC_R6M
0    2064931
1     173058
6     161856
2        151
3          3
5          1
Name: count, dtype: int64
------------------------------
방문후경과월_PC_R6M
6    2092569
0     182267
3      27879
4      27467
2      27325
5      26696
1      15797
Name: count, dtype: int64
------------------------------
방문횟수_앱_R6M
1회 이상     2082674
10회 이상      93648
20회 이상      63543
30회 이상      53407
40회 이상      44356
50회 이상      31544
60회 이상      22343
70회 이상       8170
80회 이상        315
Name: count, dtype: int64
------------------------------
방문일수_앱_R6M
0     1850835
3       43801
4       38531
2       33029
5       32669
       ...
60        244
61        114
62         38
63         14
64          3
Name: count, Length: 65, dtype: int64
------------------------------
방문월수_앱_R6M
0    1840205
6     291758
1     128752
5     108473
4      14951
2      12019
3       3842
Name: count, dtype: int64
------------------------------
방문후경과월_앱_R6M
6    1865997
0     442067
1      24231
3      18166
4      17294
2      16937
5      15308
Name: count, dtype: int64
------------------------------
방문횟수_모바일웹_R6M
0     2349905
4       32837
5        9591
3        7457
6         169
2          32
8           4
9           3
7           1
13          1
Name: count, dtype: int64
------------------------------
방문일수_모바일웹_R6M
0     2349924
3       25622
4       23438
5         700
2         311
8           4
12          1
Name: count, dtype: int64
------------------------------
방문월수_모바일웹_R6M
0    2347481
1      52519
Name: count, dtype: int64
------------------------------
방문후경과월_모바일웹_R6M
6    2370628
5       9173
4       5759
3       5084
2       4124
1       3554
0       1678
Name: count, dtype: int64
------------------------------
방문횟수_PC_B0M
0    2230827
6     102196
5      54053
7      11277
4       1399
8        241
3          6
9          1
Name: count, dtype: int64
------------------------------
방문일수_PC_B0M
0    2231071
4     119547
5      45707
3       3297
6        370
2          8
Name: count, dtype: int64
------------------------------
방문횟수_앱_B0M
0     1970714
3      105455
4      105154
5       51787
6       40352
7       33269
8       26690
9       20372
10      15735
11      11534
2        8625
12       6649
13       2759
14        716
1         123
15         64
16          2
Name: count, dtype: int64
------------------------------
방문일수_앱_B0M
0     1971052
3      164657
4       68286
5       51812
6       40395
2       40088
7       28825
8       20347
9       11281
10       2982
11        191
1          84
Name: count, dtype: int64
------------------------------
방문횟수_모바일웹_B0M
0    2399883
4        111
5          6
Name: count, dtype: int64
------------------------------
방문일수_모바일웹_B0M
0    2399890
4        110
Name: count, dtype: int64
------------------------------
인입횟수_IB_R6M
0     1716330
2      237488
3      121760
1       96051
4       73419
5       39496
6       29576
7       19914
8       18500
10      15536
9       14236
11      11246
12       6257
13        177
14         13
15          1
Name: count, dtype: int64
------------------------------
인입횟수_금융_IB_R6M
0    2400000
Name: count, dtype: int64
------------------------------
인입일수_IB_R6M
0    1719273
1     280764
2     200756
3      85427
4      44909
5      30324
6      25175
7      13339
8         33
Name: count, dtype: int64
------------------------------
인입월수_IB_R6M
0    1721061
1     431590
2     198092
3      23743
4      21658
6       3552
5        304
Name: count, dtype: int64
------------------------------
이용메뉴건수_IB_R6M
0    1722681
2     259492
1     214329
3     110172
4      53512
5      33874
6       5940
Name: count, dtype: int64
------------------------------
인입후경과월_IB_R6M
6    1752686
5     128520
4     118487
0     112078
3     106632
2      95681
1      85916
Name: count, dtype: int64
------------------------------
인입횟수_IB_B0M
0    2290196
2     109268
3        536
Name: count, dtype: int64
------------------------------
인입일수_IB_B0M
0    2310537
1      89462
2          1
Name: count, dtype: int64
------------------------------
이용메뉴건수_IB_B0M
0    2319230
1      80770
Name: count, dtype: int64
------------------------------
인입불만횟수_IB_R6M
0    2400000
Name: count, dtype: int64
------------------------------
인입불만일수_IB_R6M
0    2400000
Name: count, dtype: int64
------------------------------
인입불만월수_IB_R6M
0    2400000
Name: count, dtype: int64
------------------------------
인입불만후경과월_IB_R6M
6    2400000
Name: count, dtype: int64
------------------------------
인입불만횟수_IB_B0M
0    2400000
Name: count, dtype: int64
------------------------------
인입불만일수_IB_B0M
0    2400000
Name: count, dtype: int64
------------------------------
상담건수_B0M
0    2290448
2     109205
3        347
Name: count, dtype: int64
------------------------------
IB문의건수_사용승인내역_B0M
0    2399916
1         84
Name: count, dtype: int64
------------------------------
IB문의건수_한도_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_선결제_B0M
0    2392763
1       7237
Name: count, dtype: int64
------------------------------
IB문의건수_결제_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_할부_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_정보변경_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_결제일변경_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_명세서_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_비밀번호_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_SMS_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_APP_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_부대서비스_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_포인트_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_카드발급_B0M
0    2399995
1          5
Name: count, dtype: int64
------------------------------
IB문의건수_BL_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_분실도난_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_CA_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_CL_RV_B0M
0    2399835
1        165
Name: count, dtype: int64
------------------------------
IB문의건수_CS_B0M
0    2399623
4        369
3          8
Name: count, dtype: int64
------------------------------
IB상담건수_VOC_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB상담건수_VOC민원_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB상담건수_VOC불만_B0M
0    2400000
Name: count, dtype: int64
------------------------------
IB상담건수_금감원_B0M
0    2400000
Name: count, dtype: int64
------------------------------
상담건수_R6M
0     1686749
2      219050
3      144699
1      102229
4       78125
5       45863
6       30891
7       23119
8       19215
9       16774
10      16053
11      13643
12       3567
13         23
Name: count, dtype: int64
------------------------------
IB문의건수_사용승인내역_R6M
0    2274317
2     112250
1      13433
Name: count, dtype: int64
------------------------------
IB문의건수_한도_R6M
0    2388620
2      11380
Name: count, dtype: int64
------------------------------
IB문의건수_선결제_R6M
0    2263827
2      56263
3      42994
4      26893
5       7608
1       2295
6        120
Name: count, dtype: int64
------------------------------
IB문의건수_결제_R6M
0    2396358
2       3508
1        134
Name: count, dtype: int64
------------------------------
IB문의건수_할부_R6M
0    2399211
1        789
Name: count, dtype: int64
------------------------------
IB문의건수_정보변경_R6M
0    2361911
1      38089
Name: count, dtype: int64
------------------------------
IB문의건수_결제일변경_R6M
0    2372405
1      27587
2          5
5          3
Name: count, dtype: int64
------------------------------
IB문의건수_명세서_R6M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_비밀번호_R6M
0    2399735
1        265
Name: count, dtype: int64
------------------------------
IB문의건수_SMS_R6M
0    2398606
1       1394
Name: count, dtype: int64
------------------------------
IB문의건수_APP_R6M
0    2400000
Name: count, dtype: int64
------------------------------
IB문의건수_부대서비스_R6M
0    2399975
1         25
Name: count, dtype: int64
------------------------------
IB문의건수_포인트_R6M
0    2399952
1         47
4          1
Name: count, dtype: int64
------------------------------
IB문의건수_카드발급_R6M
0    2371084
1      28916
Name: count, dtype: int64
------------------------------
IB문의건수_BL_R6M
0    2399697
1        303
Name: count, dtype: int64
------------------------------
IB문의건수_분실도난_R6M
0    2386285
1      13715
Name: count, dtype: int64
------------------------------
IB문의건수_CA_R6M
0    2399367
1        629
8          3
2          1
Name: count, dtype: int64
------------------------------
IB문의건수_CL_RV_R6M
0    2357224
1      42658
2        117
3          1
Name: count, dtype: int64
------------------------------
IB문의건수_CS_R6M
0    2397251
4       1489
3       1008
1        251
6          1
Name: count, dtype: int64
------------------------------
IB상담건수_VOC_R6M
0    2400000
Name: count, dtype: int64
------------------------------
IB상담건수_VOC민원_R6M
0    2400000
Name: count, dtype: int64
------------------------------
IB상담건수_VOC불만_R6M
0    2400000
Name: count, dtype: int64
------------------------------
IB상담건수_금감원_R6M
0    2400000
Name: count, dtype: int64
------------------------------
불만제기건수_B0M
0    2400000
Name: count, dtype: int64
------------------------------
불만제기건수_R12M
0    2400000
Name: count, dtype: int64
------------------------------
불만제기후경과월_R12M
12    1313922
0     1086078
Name: count, dtype: int64
------------------------------
당사PAY_방문횟수_B0M
0    2400000
Name: count, dtype: int64
------------------------------
당사PAY_방문횟수_R6M
0    2400000
Name: count, dtype: int64
------------------------------
당사PAY_방문월수_R6M
0    2400000
Name: count, dtype: int64
------------------------------
당사멤버쉽_방문횟수_B0M
0     2277993
22      41109
23      28276
43      20508
42      16546
3        4854
8        2964
24       2043
1        1608
41       1385
21       1261
44        823
7         231
25        134
4         111
40         74
20         32
9          15
45         15
26          8
62          2
39          2
61          2
60          2
46          1
63          1
Name: count, dtype: int64
------------------------------
당사멤버쉽_방문횟수_R6M
0      2072232
2       112520
8        55449
216      10364
215      10293
        ...
166          1
167          1
164          1
252          1
251          1
Name: count, Length: 247, dtype: int64
------------------------------
당사멤버쉽_방문월수_R6M
0    2052315
6     208167
1     116409
2      22313
3        779
4         16
5          1
Name: count, dtype: int64
------------------------------
OS구분코드
Android    594348
IOS        172086
Name: count, dtype: int64
------------------------------
홈페이지_금융건수_R6M
0     2099135
6       66536
3       51356
4       42953
8       38373
5       31434
7       27193
9       14065
10      12535
2        5488
11       5440
12       3836
13       1170
14        420
15         37
1          29
Name: count, dtype: int64
------------------------------
홈페이지_선결제건수_R6M
0     2103789
4       41775
6       31857
5       31006
3       30510
7       30271
8       28942
9       17584
10      13733
11       9547
2        8022
12       7577
13       6049
14       5251
15       4915
16       4321
17       3975
18       3518
19       3075
20       2756
21       2439
22       2154
23       1877
24       1651
25       1153
1         865
26        768
27        412
28        157
29         42
30          9
Name: count, dtype: int64
------------------------------
홈페이지_금융건수_R3M
0    2133432
3     130798
4      88417
5      30426
6       9296
2       6254
7       1358
8         19
Name: count, dtype: int64
------------------------------

In [23]:
a1= all_df.iloc[:,2].value_counts()
print(a1.index[0], a1[0])

1회 이상 2328933

In [27]:
for i in range(1, 104) :
    a1= all_df.iloc[:,i].value_counts()
    print(a1.iloc[0])
    print('-'*30)

6
------------------------------
2328933
------------------------------
2313787
------------------------------
1683964
------------------------------
1696515
------------------------------
1880190
------------------------------
2251753
------------------------------
2250867
------------------------------
2251797
------------------------------
2221841
------------------------------
2236992
------------------------------
2064931
------------------------------
2092569
------------------------------
2082674
------------------------------
1850835
------------------------------
1840205
------------------------------
1865997
------------------------------
2349905
------------------------------
2349924
------------------------------
2347481
------------------------------
2370628
------------------------------
2230827
------------------------------
2231071
------------------------------
1970714
------------------------------
1971052
------------------------------
2399883
------------------------------
2399890
------------------------------
1716330
------------------------------
2400000
------------------------------
1719273
------------------------------
1721061
------------------------------
1722681
------------------------------
1752686
------------------------------
2290196
------------------------------
2310537
------------------------------
2319230
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2290448
------------------------------
2399916
------------------------------
2400000
------------------------------
2392763
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2399995
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2399835
------------------------------
2399623
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
1686749
------------------------------
2274317
------------------------------
2388620
------------------------------
2263827
------------------------------
2396358
------------------------------
2399211
------------------------------
2361911
------------------------------
2372405
------------------------------
2400000
------------------------------
2399735
------------------------------
2398606
------------------------------
2400000
------------------------------
2399975
------------------------------
2399952
------------------------------
2371084
------------------------------
2399697
------------------------------
2386285
------------------------------
2399367
------------------------------
2357224
------------------------------
2397251
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
1313922
------------------------------
2400000
------------------------------
2400000
------------------------------
2400000
------------------------------
2277993
------------------------------
2072232
------------------------------
2052315
------------------------------
594348
------------------------------
2099135
------------------------------
2103789
------------------------------
2133432
------------------------------

In [28]:
import pandas as pd
import csv

results = []

for i in range(1, all_df.shape[1]):
    col_name = all_df.columns[i]
    series = all_df.iloc[:, i]
    desc = series.describe()

    desc_str = f"[{col_name}]"

    # 숫자형 처리
    if pd.api.types.is_numeric_dtype(series):
        desc = desc.round().astype(int)
        zero_count = series.value_counts().get(0, 0)

        # 줄맞춰 출력 + 0의 개수 추가
        desc_text = "\n".join(f"{idx:<6} {val:>10}" for idx, val in desc.items())
        desc_str += f"\n{desc_text}\n{'0의 개수:':<6} {zero_count:>10}"
    else:
        desc_str += f"\n{series.describe().to_string()}"

    results.append(desc_str)

# CSV로 줄바꿈 포함 저장
df_result = pd.DataFrame({'통계 요약': results})
df_result.to_csv("describe_summary_with_zeros.csv", index=False, encoding='utf-8-sig', quoting=csv.QUOTE_ALL)